### ISSUE TITLE
Product Page: When you click on + display message like Item added to cart

### ISSUE THREAD

**Issue by anandnaragund** [BACreator/tulsicorp#14]
Product Page: When you click on + display a message like "Item added to cart" and give hyperlink as View Cart
When user clicks on hyperlink, control should go to Cart

**Comment by Madhuvanthi-A** [comment]
Toast message will be displayed for only 3 seconds. Hyperlink can't be given for 3 seconds message.
User have to navigate to header cart icon to view cart list.

**Comment by anandnaragund** [comment]
No message after clicking +
