### ISSUE TITLE
Cart Page: M.F.R should be renamed to MFR

### ISSUE THREAD

**Issue by anandnaragund** [BACreator/tulsicorp#16]
For the time being M.F.R should be rename. Based on Tulsi management review we will keep or remove this field

**Comment by anandnaragund** [comment]
Still I can see M.R.P. Please change it to MFR

**Comment by Madhuvanthi-A** [comment]
I have changed as per issue title "Cart Page: M.F.R should be renamed to MFR #16".
Please mention clearly which field has to change as what.
![cart](https://user-images.githubusercontent.com/21305673/160750339-9c3df451-4b6a-4afc-81b2-80b54a45d666.png)

As per above image, If I change M.R.P to MFR then there will be two fields with same name i.e., "MFR".
Help me with this confusion.
