### ISSUE TITLE
Product Page: Calculate Free Qty and display Free Qty in Product Page

### ISSUE THREAD

**Issue by anandnaragund** [BACreator/tulsicorp#28]
Calculate Free Qty and display Free Qty in Product Page. Formula is given below

FreeQty = Floor(SchemeOffer X OrderedQty) / SchemeRange

**Comment by Madhuvanthi-A** [comment]
{
      "itemMfrCode": "0001001",
      "qnty": "0",
      "itemName": "TRIACNEAL EXPERT 30ml",
      "unitPk": "30ml",
      "itemCategory": " ",
      "itemType": "NT",
      "schemeRange": "0",
      "schemeOffeQty": "0",
      "rateDiffFlag": "N",
      "schemeHalfValueFlag": " ",
      "schemeHalfValuePerc": null,
      "ratePerUnit": 1016.95
    },
